#!/usr/bin/env python3
"""Inspect public original assembly vertex data; no CAD/private asset reads."""
from pathlib import Path
import argparse,json,struct,math,hashlib
import numpy as np
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--source-root',type=Path,default=Path('mechanical/running_gear_C03'),
    help='Directory containing the extracted C03 contract, manifest and GLB (default: ./mechanical/running_gear_C03).')
parser.add_argument('--output-dir',type=Path,default=Path('steering-audit-output'),
    help='Directory containing fixtures generated by audit_c03.py; GLB evidence is written here (default: ./steering-audit-output).')
args=parser.parse_args()
ROOT=args.source_root.expanduser().resolve()
OUT=args.output_dir.expanduser().resolve()
for required in ['interface_contract_C03_R01.json','original_steering_C03_R01_manifest.json','original_steering_C03_R01.glb']:
    if not (ROOT/required).is_file():
        parser.error(f'Missing source file: {ROOT/required}. Extract the public source and GLB packages into the same directory, or set --source-root.')
if not (OUT/'independent_fixtures_C03_R01.json').is_file():
    parser.error(f'Missing fixtures in {OUT}. Run audit_c03.py with the same --source-root and --output-dir first.')
b=(ROOT/'original_steering_C03_R01.glb').read_bytes()
assert b[:4]==b'glTF'
assert struct.unpack_from('<I',b,4)[0]==2
chunks=[];off=12
while off<len(b):
    length,ctype=struct.unpack_from('<II',b,off);chunks.append((ctype,b[off+8:off+8+length]));off+=length+8
j=json.loads(chunks[0][1]);binary=next(v for k,v in chunks if k==0x004e4942)
manifest=json.loads((ROOT/'original_steering_C03_R01_manifest.json').read_text())
contract=json.loads((ROOT/'interface_contract_C03_R01.json').read_text())
rows={x['node']:x for x in manifest['assembly_nodes']};corners={x['id']:x for x in contract['corners']}
TYPES={5120:'i1',5121:'u1',5122:'<i2',5123:'<u2',5125:'<u4',5126:'<f4'}
SIZES={'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4,'MAT4':16}
def accessor(index):
    a=j['accessors'][index];v=j['bufferViews'][a['bufferView']];dt=np.dtype(TYPES[a['componentType']]);n=SIZES[a['type']]
    offset=v.get('byteOffset',0)+a.get('byteOffset',0);stride=v.get('byteStride',dt.itemsize*n)
    return np.ndarray((a['count'],n),dtype=dt,buffer=binary,offset=offset,strides=(stride,dt.itemsize)).copy()
def unit(x):return x/np.linalg.norm(x)
def line_distance(p,o,n):return float(np.linalg.norm((p-o)-np.dot(p-o,n)*n))
def axis_angle(a,b):return math.degrees(math.acos(np.clip(abs(float(np.dot(unit(a),unit(b)))),-1,1)))
def rz(a):return np.array([[math.cos(a),-math.sin(a),0],[math.sin(a),math.cos(a),0],[0,0,1]])
def rx(a):return np.array([[1,0,0],[0,math.cos(a),-math.sin(a)],[0,math.sin(a),math.cos(a)]])
def align(a,b):
    a,b=unit(a),unit(b);v=np.cross(a,b);s=np.linalg.norm(v);c=np.dot(a,b)
    if s<1e-12:return np.eye(3)
    vx=np.array([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]])
    return np.eye(3)+vx+vx@vx*((1-c)/(s*s))
def transform(c,kind,pose):
    if kind in ['fixed','rack_fixed']:return np.eye(3),np.zeros(3)
    if kind=='rack':return np.eye(3),np.array([0,pose['rackM'],0])
    if kind in ['upper','lower']:
        P=np.array(c['nominal_'+kind+'_pivot_m']);R=rx(pose['armWorldRx']);return R,P-R@P
    if kind in ['steer','spin']:
        K=np.array(c['nominal_kingpin_m']);R=rz(pose['steerRad']);return R,K+np.array(pose['uprightDeltaM'])-R@K
    if kind=='tie':
        I0=np.array(c['nominal_tie_inner_m']);O0=np.array(c['nominal_tie_outer_m']);I=np.array(pose['tieInnerM']);O=np.array(pose['tieOuterM']);R=align(O0-I0,O-I);return R,I-R@I0
    raise ValueError(kind)

node_reports=[];mesh_geometry={};axis_checks=[];failures=[]
for n in j['nodes']:
    name=n['name'];row=rows[name];m=j['meshes'][n['mesh']]
    identity=not any(k in n for k in ['matrix','translation','rotation','scale','children'])
    if not identity:failures.append(name+' has transform or children')
    if len(m['primitives'])!=1:raise ValueError('Expected one primitive')
    p=m['primitives'][0];verts=accessor(p['attributes']['POSITION']).astype(float);idx=accessor(p['indices']).reshape(-1,3)
    tri=verts[idx];anchor=verts.mean(axis=0);local=tri-anchor
    volumes=np.einsum('ij,ij->i',local[:,0],np.cross(local[:,1],local[:,2]))/6
    volume=float(volumes.sum());com=anchor+np.sum(volumes[:,None]*local.sum(axis=1)/4,axis=0)/volume
    cadcom=np.array(row['com_m']);com_error=float(np.linalg.norm(com-cadcom));vol_error=abs(volume-row['volume_m3'])/row['volume_m3']
    bounds=[verts.min(axis=0).tolist(),verts.max(axis=0).tolist()]
    contained=bool(np.all(cadcom>=verts.min(axis=0)-1e-5) and np.all(cadcom<=verts.max(axis=0)+1e-5))
    if not contained:failures.append(name+' CAD centroid outside GLB bounds')
    report={'node':name,'motion_group':row['motion_group'],'identity_transform':identity,'vertex_count':len(verts),'triangle_count':len(idx),'bounds_m':bounds,'mesh_volume_m3':volume,'relative_volume_error_vs_cad':vol_error,'mesh_com_m':com.tolist(),'com_error_vs_cad_m':com_error,'cad_com_inside_glb_bounds':contained}
    node_reports.append(report)
    # Integrated volume covariance avoids the density bias of vertex-sampling PCA.
    # A tetrahedron's E[xx^T] equals (sum(v)sum(v)^T + sum(vv^T))/20.
    sums=local.sum(axis=1)
    raw_moment=(np.einsum('i,ij,ik->jk',volumes,sums,sums)+np.einsum('i,imj,imk->jk',volumes,local,local))/20/volume
    relative_com=com-anchor
    covariance=raw_moment-np.outer(relative_com,relative_com)
    eigenvalues,eigenvectors=np.linalg.eigh(covariance);major=eigenvectors[:,-1];minor=eigenvectors[:,0]
    mesh_geometry[name]={'major':major,'minor':minor,'com':com}
    for cid,c in corners.items():
        if not name.startswith(cid+'_'):continue
        kind=None;axis=None;origin=None
        if name.endswith('_inner_tie_pin'):
            kind='inner_tie_pin';axis=np.array(c['inner_pin_axis']);origin=np.array(c['nominal_tie_inner_m']);measured=major
        elif name.endswith('_outer_tie_pin'):
            kind='outer_tie_pin';axis=np.array(c['inner_pin_axis']);origin=np.array(c['nominal_tie_outer_m']);measured=major
        elif '_tie_tube_' in name or '_tie_insert_' in name:
            kind='tie_line';origin=np.array(c['nominal_tie_inner_m']);axis=unit(np.array(c['nominal_tie_outer_m'])-origin);measured=major
        elif name.endswith('_wheel_adapter'):
            kind='wheel_axis';origin=np.array(c['nominal_wheel_center_m']);axis=np.array([0,c['side'],0]);measured=minor
        if kind:
            angle=axis_angle(measured,axis);distance=line_distance(com,origin,unit(axis))
            axis_checks.append({'node':name,'kind':kind,'axis_angle_error_deg':angle,'centroid_to_expected_axis_m':distance,'measured_axis_unsigned':measured.tolist(),'expected_axis':axis.tolist()})

fixtures=json.loads((OUT/'independent_fixtures_C03_R01.json').read_text())['fixtures']
# Exercise actual GLB geometry axes and centroids through the proposed transforms.
transformed_checks=[]
for fixture in fixtures:
    if fixture['input']['kind']!='boundary_grid':continue
    c=corners[fixture['input']['corner_id']];pose=fixture['expected']
    for initial in axis_checks:
        name=initial['node']
        if not name.startswith(c['id']+'_'):continue
        group=rows[name]['motion_group'];kind=group[len(c['id'])+1:] if group.startswith(c['id']+'_') else 'rack'
        R,t=transform(c,kind,pose);geo=mesh_geometry[name];com=R@geo['com']+t;measured=R@np.array(initial['measured_axis_unsigned'])
        what=initial['kind']
        if what=='tie_line':origin=np.array(pose['tieInnerM']);expected=unit(np.array(pose['tieOuterM'])-origin)
        elif what=='inner_tie_pin':origin=np.array(pose['tieInnerM']);expected=np.array(pose['innerTiePinAxis'])
        elif what=='outer_tie_pin':origin=np.array(pose['tieOuterM']);expected=np.array(pose['outerTiePinAxis'])
        elif what=='wheel_axis':origin=np.array(pose['wheelCenterM']);expected=np.array(pose['wheelAxis'])
        transformed_checks.append({'corner':c['id'],'q_rad':pose['q'],'rack_m':pose['rackM'],'node':name,'motion_group':group,'axis_angle_error_deg':axis_angle(measured,expected),'centroid_to_current_axis_m':line_distance(com,origin,unit(expected)),'rotation_determinant':float(np.linalg.det(R))})

summary={'glb_node_count':len(j['nodes']),'manifest_node_count':len(rows),'unique_glb_names':len(set(n['name'] for n in j['nodes'])),'names_match_manifest':set(n['name'] for n in j['nodes'])==set(rows),'all_nodes_identity':all(x['identity_transform'] for x in node_reports),'all_nodes_direct_scene_roots':set(j['scenes'][j['scene']]['nodes'])==set(range(len(j['nodes']))),'source_up_axis':j.get('extras',{}).get('upAxis'),'source_units':j.get('extras',{}).get('units'),'max_tessellated_com_error_vs_cad_m':max(x['com_error_vs_cad_m'] for x in node_reports),'max_tessellated_relative_volume_error':max(x['relative_volume_error_vs_cad'] for x in node_reports),'max_nominal_axis_error_deg':max(x['axis_angle_error_deg'] for x in axis_checks),'max_nominal_centroid_to_axis_m':max(x['centroid_to_expected_axis_m'] for x in axis_checks),'transformed_axis_checks':len(transformed_checks),'max_transformed_axis_error_deg':max(x['axis_angle_error_deg'] for x in transformed_checks),'max_transformed_centroid_to_axis_m':max(x['centroid_to_current_axis_m'] for x in transformed_checks),'max_rotation_determinant_error':max(abs(x['rotation_determinant']-1) for x in transformed_checks),'failures':failures,'notes':['Geometry-only mesh fit check. Mesh-versus-CAD centroid/volume deviations include tessellation and are not tolerances or physical qualification.','Axes use integrated tetrahedral volume covariance of the GLB triangles, avoiding nonuniform vertex-sampling bias; small deviations are tessellation/numeric effects.','Transforms use already-baked world coordinates: arms P + Rx(x-P); steer delta + K + Rz(x-K); tie Icurrent + Ralign(x-Inominal); rack x+[0,r,0].','Middle C02 fixed-steer corners are excluded from this C03 assembly.']}
summary['pass']=not failures and summary['names_match_manifest'] and summary['all_nodes_identity'] and summary['all_nodes_direct_scene_roots'] and summary['max_nominal_axis_error_deg']<0.1 and summary['max_transformed_axis_error_deg']<0.1 and summary['max_nominal_centroid_to_axis_m']<1e-5 and summary['max_transformed_centroid_to_axis_m']<1e-5
(OUT/'glb_alignment_audit.json').write_text(json.dumps({'summary':summary,'node_reports':node_reports,'nominal_axis_checks':axis_checks,'transformed_checks':transformed_checks},indent=2)+'\n')
print(json.dumps(summary,indent=2))

if not summary['pass']:raise SystemExit(1)
