from pathlib import Path
import json,csv
P=Path(__file__).parent
sources=[
{'id':'RELION-48V030-GC2','manufacturer':'RELiON / Navico','component':'InSight 48V 30Ah 48V030-GC2','source_url':'https://www.relionbattery.com/products/lithium/insight-gc2-48v','drawing_url':'https://relion-battery.s3.us-east-1.amazonaws.com/docs/product/InSightDataSheet_48V_240425_110052.pdf','accessed_utc':'2026-10-09','primary_source':True,'dimensions_mm':[260,180,276],'mass_kg':15.6,'source_CAD_acquired':False,'model_class':'original dimensional envelope only','redistribution':'No supplier CAD or artwork included. Manufacturer datasheet linked, not copied into deliverable. Original reservation cuboid encodes factual overall dimensions only.','facts':{'nominal_voltage_V':51.2,'capacity_Ah':30,'energy_Wh':1536,'parallel_units_max':10,'series_allowed':False,'recommended_continuous_discharge_A_each':45,'maximum_continuous_discharge_A_each':100,'peak_charge_V':57,'continuous_charge_A_each_max':30},'limits':['Individual published ratings do not establish rover system limits.','Four proposed parallel units reserve 62.4kg and 6144Wh nominal. This is not a runtime claim.','Do not use golf-cart mileage claims for this rover.','Inrush, regen acceptance, BMS sharing, fusing, contactors, charging and thermal design remain unqualified.','Battery terminal/handle positions and supplier hold-down details are not modeled.']},
{'id':'UR-OEM-DC','manufacturer':'Universal Robots','component':'OEM DC control box dimensional reservation','source_url':'https://www.universal-robots.com/manuals/EN/HTML/SW5_25/Content/prod_oem_cb_all/oem_cb_all_specs_root.htm','product_url':'https://www.universal-robots.com/products/cb5-oem/','supplier_CAD_page':'https://www.universal-robots.com/download/mechanical-e-series/control-box-oem/control-box-3d-step-file-cb55cb56-oem-ac-dc-ur-series-e-series/','accessed_utc':'2026-10-09','primary_source':True,'dimensions_mm_WHD':[451,150,168],'mass_kg':4.3,'source_CAD_acquired':False,'model_class':'original dimensional envelope only','redistribution':'Supplier STEP available behind account gate under Graphical Documentation terms. No file downloaded, copied or republished. Reservation is our dimensional cuboid.','facts':{'input_min_VDC':19,'input_typical_VDC':[24,48],'input_max_VDC':72,'inrush_A_max':400,'external_fuse_A_max':100,'UR20_control_unit_heat_W_max':350},'limits':['OEM DC controller choice is provisional; exact controller revision and robot compatibility need supplier confirmation.','A 51.2V nominal battery being inside the published input range does not qualify the power architecture.','400A inrush requires verified start-up/soft-start design; do not assume battery bank supplies both controllers at once.','350W maximum control-unit heat per UR20 means 700W for two as a thermal sizing bound, not measured operating dissipation.','Standard enclosed control boxes use AC; no claim the battery directly powers them.','No vendor mounting hole positions, connector geometry, cooling clearances or orientations inferred.']},
{'id':'VIC-ORION-CANDIDATE','manufacturer':'Victron Energy','component':'Orion-Tr 48/12-30 360W auxiliary converter, research candidate only','source_url':'https://www.victronenergy.com/media/pricelist/Pricelist_Victron_EUR_C_2026-Q2_web.pdf','accessed_utc':'2026-10-09','primary_source':True,'dimensions_mm_HWD':[130,186,80],'mass_kg':1.8,'source_CAD_acquired':False,'model_class':'not modeled, unselected candidate','redistribution':'Source link only, no supplier geometry','limits':['No electrical selection or purchase.','Exact converter supply range, cooling, isolation and transient compatibility must be verified before modeling integration.']}
]
(P/'SOURCES.json').write_text(json.dumps(sources,indent=2))
rows=[['RELiON 48V030-GC2','RELiON','4','dimensional envelope, not detailed supplier CAD','260×180×276','15.6',sources[0]['source_url'],'Proposed 51.2V parallel bank only; electrical and hold-down qualification outstanding'],['OEM DC control box','Universal Robots','2','dimensional envelope, not detailed supplier CAD','451×150×168','4.3',sources[1]['source_url'],'Revision compatibility, inrush, mounting and thermal validation outstanding'],['Orion-Tr 48/12-30','Victron Energy','0','research candidate, not modeled','130×186×80','1.8',sources[2]['source_url'],'Not selected or purchased']]
with (P/'sourced_bom.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['component','manufacturer','reserved_quantity','CAD_classification','source_dimensions_mm','source_mass_kg_each','primary_source','selection_limit']);w.writerows(rows)
